### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by nozpheratu** [grycap/scar#204]
I'm working with a custom image -- it's not particularly large -- it's based on the same ffmpeg image used in the example with a few additional packages. 

It shows up as 237MB when I run `docker images`. 

My container is running a bash script that runs some ffmpeg + imagemagick commands, and it's failing with error like below:
> convert: AnErrorHasOccurredWritingToFile `/tmp/diascope/out_TMP/path-i001.png': No space left on device

I didn't think I was hitting the 500MB `/tmp` restriction -- and I double checked my available diskspace with a `df -h`:

> Filesystem Size Used Avail Use% Mounted on
/dev/xvda1 526M 383M 132M 75% /
/dev/xvda1 30G 4.8G 25G 17% /dev

It seems to hit this disk space warning almost instantly after my script runs, so that eliminates the possibility of the disk space suddenly hitting capacity mid-script.

Not sure how to proceed on this, does anybody have any ideas?

**Comment by nozpheratu** [comment]
Here's my Dockerfile on the off-chance that anything can be gleaned. Note the content of the two `COPY` directories is < 10MB, so I doubt that's it:

```
FROM sameersbn/ffmpeg

ENV DIASCOPE_VERSION=0.2.1e

RUN apt-get update && apt-get install --no-install-recommends -y imagemagick sox gawk wget && \
wget --no-check-certificate "https://downloads.sourceforge.net/project/diascope/diascope/diascope-${DIASCOPE_VERSION}.tgz" && \
tar -xzf "diascope-${DIASCOPE_VERSION}.tgz" && \
mv "/tmp/diascope-${DIASCOPE_VERSION}" "/usr/lib/diascope" && \
cd "/usr/lib/diascope" &&  \
/bin/sh install.sh && \
ln -s "diascope" "/usr/bin/" && \
apt-get clean autoclean && \
apt-get purge -y --auto-remove wget systemd python && \
rm -rf /var/lib/apt /var/lib/dpkg /var/lib/cache /var/lib/log /tmp/* /var/log/*

COPY assets/ /assets/
COPY scripts/ /scripts/

ENTRYPOINT ["/bin/bash"]
```

**Comment by alpegon** [comment]
Hi @nozpheratu, 

How many invocations are you launching at the same time?

It seems that you are placing the output images in the folder `/tmp/diascope/out_TMP/` which (I'm assuming) is not unique and is not deleted after each lambda iteration and that could lead to filling all the space. Doing a `df -h` could not show the problem because it's only launched once so no other functions are using the space at the same time.

Have in mind that the ephemeral disk space (i.e. /tmp ) is reused between invocations of the same function and that could lead to running out of space if the files that your script generates are not being deleted. SCAR only manages the files placed in the output folder of the container (i.e. /tmp/$REQUEST_ID/output)(if any).
To better understand how to process hundreds of images at the same time you can check the workflow presented in the [ffmpeg example](https://github.com/grycap/scar/tree/master/examples/ffmpeg#creating-the-file-processing-script).

Regards

**Comment by nozpheratu** [comment]
@alpegon Thanks for the reply. It looks to be a two-fold thing, some ephemeral data was sticking around from previous function calls, and also after some more analysis, it turned out that my script was bloating one of the `/tmp` folders up past 100MB during runtime. 

I managed to shave an additional 50MB off of my image which seemed to do the trick for now.
