### ISSUE TITLE
Pull From Private Docker Repository

### ISSUE THREAD

**Issue by ozgurdemir** [grycap/scar#244]
It would be nice to be able to pull from a private docker repository like AWS Elastic Container Registry.

**Comment by gmolto** [comment]
Hi @ozgurdemir. 

Since SCAR relies on [udocker](https://github.com/indigo-dc/udocker) to pull the images from the Docker Registry, this support should be introduced in uDocker. In the meantime, you can include the Docker image as part of the deployment package (see: https://github.com/grycap/scar#upload-docker-image-files-using-an-s3-bucket).

Cheers.

**Comment by bmallary** [comment]
@ozgurdemir 

I encountered the same issue... I did not want to push a docker image to the Docker Registry.  This can be avoided by saving the docker image using "docker save" to tar, and then creating a tarball via gzip.  SCAR can accept this image via the -if parameter, and then storing it to S3 via -db.

HTH

**Comment by ozgurdemir** [comment]
Thanks for the replies. I've already tried to load the docker image from S3. However, this reduces the docker image size from 512Mb to 200isch Mb which was too small for me. Ended up using AWS batch for my task.

**Comment by alpegon** [comment]
Yep, @ozgurdemir that's true, loading images from S3 limits the size even more due to lambda restrictions (it's 250 MB **uncompressed**) as explained here https://docs.aws.amazon.com/lambda/latest/dg/limits.html.
Anyway, thanks for the responses and for trying SCAR :smile:
