### ISSUE TITLE
Your website is 404

### ISSUE THREAD

**Issue by dankohn** [grycap/scar#274]
You link to https://grycap.github.io/scar/ but it's currently 404.

**Comment by gmolto** [comment]
Hi @dankohn. Thank you for noticing this. We want to rely on the readthedocs documentation page (https://scar.readthedocs.io/en/latest/) instead of the old web in order to better keep up with the changes in the framework. This is why we decommissioned last week the web page.

We want to introduce the change on the CNCF entry (https://landscape.cncf.io/selected=scar) so that the website attribute now links to the readthedocs site. 

Should we do another PR to introduce this change?

Thanks.

**Comment by dankohn** [comment]
Updated here, thanks: https://github.com/cncf/landscape/commit/b6aff71abaf0c594e9df602d01809a352fa211a2
