### ISSUE TITLE
Can I use this lambda for training?

### ISSUE THREAD

**Issue by vfbsilva** [grycap/scar#349]

**Comment by gmolto** [comment]
Hi. Thank you for your interest in SCAR. Could you please better describe the use case that you would like to achieve?

**Comment by vfbsilva** [comment]
My bad, I was sort of spamming. I want to run darknet (a neural network) https://github.com/AlexeyAB. https://github.com/grycap/scar/blob/master/examples/darknet/README.md. But your samples show the result of detection whereas im interested in training.

**Comment by gmolto** [comment]
Training in AWS Lambda seems unfeasible due the strict computing constraints (< 15 minutes; < 3008 MB of RAM). But if you resort to the AWS Batch integration with SCAR (see: https://scar.readthedocs.io/en/latest/batch.html) then you can bypass these limits since you will be executing anything as a Docker-based job on a dynamically provisioned EC2 instance.
